#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiseLabs.Analytics
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Nuget\DashboardPage.cshtml"
    using System.Configuration;
    
    #line default
    #line hidden
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Nuget\DashboardPage.cshtml"
    using WiseLabs.Analytics;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class DashboardPage : WebTemplateBase
    {
#line hidden
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<h1");

WriteLiteral(" id=\"PageTitle\"");

WriteLiteral(@">
    Dashboard
</h1>

<style>
    .funnel { box-sizing: border-box; list-style-type: none; background-color: #ddd; margin: 0px; padding: 0px; width: 300px; }
    .funnel li .bar { background-color: #000; }
    .funnel li + li .bar { background-color: #333; }
    .funnel li + li + li .bar { background-color: #666; }
    .funnel li + li + li + li .bar { background-color: #999; }
    .funnel li + li + li + li + li .bar { background-color: #ccc; }

    .funnel li {
     width: 300px;   
     position: relative;
     height: 40px;
    }

    .text {
         position: absolute;   
         text-align: center;
         color: #fff; 
         width: 100%;
         top: 10px;
    }

    .bar {
         position: absolute;   
         height: 40px;
    }
</style>

");

            
            #line 38 "..\..\Nuget\DashboardPage.cshtml"
  
    var cohorts = Tracker.GetEvents().GroupBy(x => x.CohortName).OrderBy(x => x.Key);
    var funnel = ConfigurationManager.AppSettings["WiseLabs.Analytics.Funnel"].Split(',');

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 43 "..\..\Nuget\DashboardPage.cshtml"
 foreach (var cohort in cohorts)
{
    var firstEvent = cohort.SingleOrDefault(x => x.EventName == funnel[0]);
    var max = firstEvent == null ? 0 : firstEvent.EventCount;
    if (max != 0)
    {

            
            #line default
            #line hidden
WriteLiteral("        <h3>");

            
            #line 49 "..\..\Nuget\DashboardPage.cshtml"
       Write(cohort.Key);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n");

WriteLiteral("        <ul");

WriteLiteral(" class=\"funnel\"");

WriteLiteral(">\r\n\r\n");

            
            #line 52 "..\..\Nuget\DashboardPage.cshtml"
            
            
            #line default
            #line hidden
            
            #line 52 "..\..\Nuget\DashboardPage.cshtml"
             foreach (var step in funnel)
            {
                var e = cohort.SingleOrDefault(x => x.EventName == step);
                var percent = e == null ? 0 : e.EventCount * 100 / max;
                var pixels = percent * 3;


            
            #line default
            #line hidden
WriteLiteral("                <li>\r\n");

WriteLiteral("                    ");

            
            #line 59 "..\..\Nuget\DashboardPage.cshtml"
               Write(WiseLabs.Analytics.Html.Raw("<div class='bar' style='width: " + pixels + "px;'></div>"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <span");

WriteLiteral(" class=\"text\"");

WriteLiteral(">");

            
            #line 60 "..\..\Nuget\DashboardPage.cshtml"
                                   Write(step + ": " + percent + "% (" + (e == null ? 0 : e.EventCount) + ")");

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </li>\r\n");

            
            #line 62 "..\..\Nuget\DashboardPage.cshtml"
                
            }

            
            #line default
            #line hidden
WriteLiteral("        </ul>\r\n");

            
            #line 65 "..\..\Nuget\DashboardPage.cshtml"
    }
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<p>\r\n    Generated by Visual Studio extension RazorGenerator: https://visualstu" +
"diogallery.msdn.microsoft.com/1f6ec6ff-e89b-4c47-8e79-d2d68df894ec\r\n</p>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
