#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiseLabs.Analytics
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 1 "..\..\Nuget\DashboardPage.cshtml"
    using WiseLabs.Analytics;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class DashboardPage : WebTemplateBase
    {
#line hidden
        public override void Execute()
        {
WriteLiteral("<h1");

WriteLiteral(" id=\"PageTitle\"");

WriteLiteral(">\r\n    Dashboard\r\n</h1>\r\n\r\nHello world\r\n\r\n<p>\r\n    Generated by Visual Studio ext" +
"ension RazorGenerator: https://visualstudiogallery.msdn.microsoft.com/1f6ec6ff-e" +
"89b-4c47-8e79-d2d68df894ec\r\n</p>\r\n");

        }
    }
}
#pragma warning restore 1591
